table d_favorecido_plano
	lineageTag: 54e3e631-2a23-41f0-bbee-6a6726c08b8e

	column ne_ccor_favorecido
		dataType: string
		lineageTag: 532b38b8-dc7a-4b2c-b674-df8c46ebf8e3
		summarizeBy: none
		sourceColumn: ne_ccor_favorecido

		annotation SummarizationSetBy = Automatic

	column ne_ccor_favorecido_descricao
		dataType: string
		lineageTag: 3f3764e4-9ff0-47c7-8cdd-502c4195fdeb
		summarizeBy: none
		sourceColumn: ne_ccor_favorecido_descricao

		annotation SummarizationSetBy = Automatic

	partition d_favorecido_plano = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\00878168141\Documents\projeto MIR\BancoDadosSistema\planoDeAcao\d_favorecido_plano.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Column1", type text}, {"Column2", type text}}),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Tipo Alterado", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ne_ccor_favorecido", type text}, {"ne_ccor_favorecido_descricao", type text}})
				in
				    #"Tipo Alterado1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

